### ISSUE TITLE
Problem with: Deploying Portainer behind nginx reverse proxy

### ISSUE THREAD

**Issue by garutilorenzo** [portainer/portainer-docs#217]
I found a problem with [this ](https://github.com/portainer/portainer-docs/blob/ce-2.9/advanced/reverse-proxy/nginx.md) documentation.
The Deploying in a Docker Swarm scenario is not alwasy correct/true.
Using jwilder/nginx-proxy image both jwilder/nginx-proxy and portainer/portainer-ce:latest must be created and must be running on the same manager machine.

If the docker swarm has many docker swarm managers and nginx-proxy container and portainer-ce container are scheduled on different manager host the nginx configuration wont be regenerated.

One possible solution is for example adding a placement constraint based on the manager hostname:

```
version: '3.2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - proxy
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./vhost.d:/etc/nginx/vhost.d:ro"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
          - node.hostname == node.example.com

  agent:
    image: portainer/agent:latest
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - data:/data
    environment:
      - VIRTUAL_HOST=portainer.yourdomain.com
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
    networks:
      - proxy
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
          - node.hostname == node.example.com


networks:
  proxy:
    external: true
  agent_network:
    external: true

volumes:
   data:
```
