### ISSUE TITLE
Agent deployment on windows server fails pipe volume  syntax.

### ISSUE THREAD

**Issue by HollisTech** [portainer/portainer-docs#261]
The binding for  for a named pipe volume has to specify type 'npipe'.
> Error response from daemon: invalid volume specification: 'C:\Users\foo\Documents\portainer-agent\pipe\docker_engine:\\.\pipe\docker_engine:rw': invalid mount config for type "bind": bind source path does not exist: c:\users\foo\documents\portainer-agent\pipe\docker_engine

For example, in a docker compose yaml file:
```
    volumes:
      - C:\:C:\host
      - C:\ProgramData\docker\volumes:C:\ProgramData\docker\volumes
      - source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
        type: npipe
```
