### ISSUE TITLE
Document using compose for both ce and premium 

### ISSUE THREAD

**Issue by sbe-arg** [portainer/portainer-docs#268]
Something on the lines of:

```yaml
version: '3.9'

name: 'services'

services:

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: docker.io/containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  portainer:
    container_name: portainer
    hostname: portainer
    image: docker.io/portainer/portainer-ce:latest
    command: --tlsskipverify --admin-password "$$2y$$05$$YhkVSP6tIoP2xVByx.8SdOjd9MJrcR/U9w6rv51GuSpUHkJvEsW9i"
    # docker run --rm httpd:alpine htpasswd -nbB admin supersecurepassword | cut -d ":" -f 2 # comment each $ with another $
    ports:
      - 127.0.0.1:9443:9443
      - 127.0.0.1:8000:8000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

volumes:
  portainer_data: {}
```
